version: 2

jobs:

  build:
    docker: [{ image: 'circleci/openjdk:8u181-node' }]
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
    steps:
      - checkout
      - restore_cache: { key: 'gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}' }
      - restore_cache: { key: 'gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}' }
      - run: ./gradlew --no-daemon --parallel --stacktrace  --continue --max-workers=2 --profile build
      - save_cache:
          key: 'gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}'
          paths: [ ~/.gradle/wrapper ]
      - save_cache:
          key: 'gradle-cache-v2-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}'
          paths: [ ~/.gradle/caches ]
    #   - deploy:
    #       command: |
    #         # publishing snapshots to bintray does not work, so we only publish from tag builds (not develop)
    #         if [[ "${CIRCLE_TAG}" =~ [0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)* ]]; then
    #           ./gradlew --no-daemon --parallel --stacktrace  --continue --max-workers=2 --profile publish
    #         else
    #           ./gradlew --no-daemon --parallel --stacktrace  --continue --max-workers=2 --profile publishToMavenLocal
    #           mkdir -p $CIRCLE_ARTIFACTS/poms
    #           find . -name 'pom-default.xml' -exec cp --parents {} $CIRCLE_ARTIFACTS/poms \;
    #         fi
      - store_test_results: { path: ~/junit }
      - store_artifacts: { path: ~/artifacts }

  build-11:
    docker: [{ image: 'circleci/openjdk:11-node' }]
    environment:
      GRADLE_OPTS: -Dorg.gradle.console=plain -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      CIRCLE_TEST_REPORTS: /home/circleci/junit
      CIRCLE_ARTIFACTS: /home/circleci/artifacts
    steps:
      - checkout
      - restore_cache: { key: 'gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}' }
      - restore_cache: { key: 'gradle-cache-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}' }
      - run: ./gradlew --no-daemon --parallel --stacktrace  --continue --max-workers=2 --profile build
      - save_cache:
          key: 'gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}'
          paths: [ ~/.gradle/wrapper ]
      - save_cache:
          key: 'gradle-cache-v2-{{ checksum "versions.props" }}-{{ checksum "build.gradle" }}'
          paths: [ ~/.gradle/caches ]
      - store_test_results: { path: ~/junit }
      - store_artifacts: { path: ~/artifacts }

workflows:
  version: 2
  build:
    jobs:
      - build: { filters: { tags: { only: /.*/ } } }
      - build-11: { filters: { tags: { only: /.*/ } } }
